/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampusMapRouteImport } from './routes/campus-map'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as AuthenticatedMyDashboardRouteImport } from './routes/_authenticated/my-dashboard'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AthletesAthleteIdRouteImport } from './routes/athletes.$athleteId'
import { Route as SportsSportIdRouteImport } from './routes/sports.$sportId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments.$tournamentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusMapRoute = CampusMapRouteImport.update({
  id: '/campus-map',
  path: '/campus-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyDashboardRoute =
  AuthenticatedMyDashboardRouteImport.update({
    id: '/my-dashboard',
    path: '/my-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AthletesAthleteIdRoute = AthletesAthleteIdRouteImport.update({
  id: '/$athleteId',
  path: '/$athleteId',
  getParentRoute: () => AthletesRoute,
} as any)
const SportsSportIdRoute = SportsSportIdRouteImport.update({
  id: '/$sportId',
  path: '/$sportId',
  getParentRoute: () => SportsRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => TournamentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/auth': typeof AuthRoute
  '/campus-map': typeof CampusMapRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/facilities': typeof FacilitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/auth': typeof AuthRoute
  '/campus-map': typeof CampusMapRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/facilities': typeof FacilitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/athletes': typeof AthletesRouteWithChildren
  '/auth': typeof AuthRoute
  '/campus-map': typeof CampusMapRoute
  '/certificates': typeof CertificatesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/facilities': typeof FacilitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/_authenticated/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/athletes'
    | '/auth'
    | '/campus-map'
    | '/certificates'
    | '/dashboard'
    | '/explore'
    | '/facilities'
    | '/reset-password'
    | '/sports'
    | '/teams'
    | '/tournaments'
    | '/my-dashboard'
    | '/portal'
    | '/athletes/$athleteId'
    | '/sports/$sportId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/athletes'
    | '/auth'
    | '/campus-map'
    | '/certificates'
    | '/dashboard'
    | '/explore'
    | '/facilities'
    | '/reset-password'
    | '/sports'
    | '/teams'
    | '/tournaments'
    | '/my-dashboard'
    | '/portal'
    | '/athletes/$athleteId'
    | '/sports/$sportId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/athletes'
    | '/auth'
    | '/campus-map'
    | '/certificates'
    | '/dashboard'
    | '/explore'
    | '/facilities'
    | '/reset-password'
    | '/sports'
    | '/teams'
    | '/tournaments'
    | '/_authenticated/my-dashboard'
    | '/_authenticated/portal'
    | '/athletes/$athleteId'
    | '/sports/$sportId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AthletesRoute: typeof AthletesRouteWithChildren
  AuthRoute: typeof AuthRoute
  CampusMapRoute: typeof CampusMapRoute
  CertificatesRoute: typeof CertificatesRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FacilitiesRoute: typeof FacilitiesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SportsRoute: typeof SportsRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-map': {
      id: '/campus-map'
      path: '/campus-map'
      fullPath: '/campus-map'
      preLoaderRoute: typeof CampusMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-dashboard': {
      id: '/_authenticated/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof AuthenticatedMyDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/athletes/$athleteId': {
      id: '/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof AthletesAthleteIdRouteImport
      parentRoute: typeof AthletesRoute
    }
    '/sports/$sportId': {
      id: '/sports/$sportId'
      path: '/$sportId'
      fullPath: '/sports/$sportId'
      preLoaderRoute: typeof SportsSportIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyDashboardRoute: typeof AuthenticatedMyDashboardRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyDashboardRoute: AuthenticatedMyDashboardRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AthletesRouteChildren {
  AthletesAthleteIdRoute: typeof AthletesAthleteIdRoute
}

const AthletesRouteChildren: AthletesRouteChildren = {
  AthletesAthleteIdRoute: AthletesAthleteIdRoute,
}

const AthletesRouteWithChildren = AthletesRoute._addFileChildren(
  AthletesRouteChildren,
)

interface SportsRouteChildren {
  SportsSportIdRoute: typeof SportsSportIdRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportIdRoute: SportsSportIdRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AthletesRoute: AthletesRouteWithChildren,
  AuthRoute: AuthRoute,
  CampusMapRoute: CampusMapRoute,
  CertificatesRoute: CertificatesRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FacilitiesRoute: FacilitiesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SportsRoute: SportsRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
